### ISSUE TITLE
Stays do not always stay

### ISSUE THREAD

**Issue by ghost** [Nocte-/rhea#40]
Hi!

So... as discussed on Slack, I have been having trouble with stays not really having the desired effect all of the time. Indeed, quite often, when I add or remove constraints, variables jump around even though they should not. This have driven me crazy for some time and led to resort to all kinds of hacks. Because I use Rhea via aqt-cassowary [1], this has been very hard to reproduce -- this library usually manipulate the solver in non-deterministic, but in theory correct, orders.

So, **finally** I have been able to write a test that fails sistematically in my machine here. I have two variations of the test, that execute the sames calls in different order. In one it fails, in the other it passes. Funny thing is, the failing test requires only to change the order in which variables are declared just to make it pass. Crazy shit.

So, here are the tests:
https://github.com/jbo-ableton/rhea/commit/adbfdf51d48dc956521706b1473276b20ac8e563

[1] https://github.com/AbletonAG/aqt-cassowary

**Comment by hfossli** [comment]
Do you use stays a lot? There's been some discussion wether stays should be removed or not. Do you have any strong opinions on this matter?

**Comment by jbo-ableton** [comment]
@hfossli There are some cases where I found it necessary. Because of the bugs Stays have in Rhea I ended up simulating them as a feedback loop with a "edit" constraint that is fed back into a variable. There was some discussion about this on Slack some time ago... I remember proposing a different system where instead of edit and stays we split variables into "input variables" and "output variables". The output ones are similar to the ones we have now, input variables have values that are always set explicitly by the programmer. An input plus a constraint is like and edit. A stay can be achieved by binding an input to an output.

**Comment by helmesjo** [comment]
Any progress on this? I tried kiwi but without stays it feels risky since "hacking" in stays is not really desirable in my situation... I'm thinking about swopping it out for Nocte but don't wanna put too much effort into it if there might give other issues.

OT: How is the performance compared to kiwi?

**Comment by Nocte-** [comment]
@helmesjo I've removed stays from the 0.3 branch. I couldn't get them to work reliably in the same way as Cassowary does, and for many applications they're not needed anyway. The plan was to add them separately, for example like @ghost described.

If I remember correctly, 0.2 is a bit slower than Kiwi, 0.3 is about as fast. If you already have something working with Kiwi, I'd recommend staying with it.
